version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_HOST
    volumes:
      - .etc/docker/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 10s
      retries: 5

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    depends_on:
      - mysql
    ports:
      - '8888:8080'
    links:
      - mysql
      - maildev
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      KEYCLOAK_PASSWORD: 'admin'
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_LOGLEVEL: 'INFO'
      ROOT_LOGLEVEL: 'INFO'
      DEBUG: 'true'
      DEBUG_PORT: "*:8787"

  maildev:
    container_name: maildev
    image: djfarrelly/maildev:1.0.0-rc2
    ports:
      - '9999:80'
      - '25'
